# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: DevOps

variables:
  var1: 10
  staticvar: 'myvalue'
  compilevar: ${{ variables.staticvar }}
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

stages:
- stage: A
  displayName: "Stage-A Build and Test"
  variables:
  - name: var2
    value: 100
  jobs:
  - job: A1
    displayName: "Job-A1 build"
    steps:
    - script: |
        echo "Building the application in A1"
        echo ${{ variables.staticvar }}
        echo $(compilevar)
        echo $(isMain)
      displayName: "Build Step"
  - job: A2
    displayName: "Job A2 Test"
    dependsOn: A1
    condition: succeeded()
    timeoutInMinutes: 10
    cancelTimeoutInMinutes: 2
    workspace: 
     clean: all
    steps:
    - script: echo "Building the application in A2"
      displayName: "Test Step"

  - job: A3
    steps:
    - bash: echo "##vso[task.setvariable variable=shouldrun;isOutput=true]true"
      # or on Windows:
      # - script: echo ##vso[task.setvariable variable=shouldrun;isOutput=true]true
      name: printvar
      displayName: "defining the varialbe"

  - job: A4
    condition: and(succeeded(), eq(dependencies.A.outputs['printvar.shouldrun'], 'true'))
    dependsOn: A3
    steps:
    - script: echo hello from A4
      
- stage: B
  displayName: "Stage-B Deploy"
  jobs:
  - job: B1
    displayName: "Stage B1 Deploy"
    steps:
    - script: echo "Building the application B1"




