# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: DevOps

variables:
- name: var1
  value: 10
- group: vargroup1

stages:
- stage: A
  displayName: "Stage-A Build and Test"
  jobs:
  - job: A1
    displayName: "Job-A1 build"
    steps:
    - script: echo "Building the application in A1"
      displayName: "Build Step"
  - job: A2
    displayName: "Job A2 Test"
    steps:
    - script: echo "Building the application in A2"
      displayName: "Test Step"
      
- stage: B
  displayName: "Stage-B Deploy"
  jobs:
  - job: B1
    displayName: "Stage B1 Deploy"
    steps:
    - script: echo "Building the application B1"



